name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3    
      - name: Search
        run : grep -Pnr --include=*.properties '(?i)^.*(dev.mad.tla.abc.com)\\s*[=:]\\s*(?!cyberark|false)\\S+\r?$'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Clean Install
        run: mvn clean install
