name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3      
      - name: Clean Install
        run: mvn clean install
