name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3    
      - name: Search
        run : grep -Pnr --include=*.properties "(?i)^.*(demo)\\s*[=:]\\s*(?!cyberark|false)\\S+\r?$"    
