name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3          
      - name: Grep command
        run: grep -Pnr --include=*.properties '=\w*(?aei.abc.amar.com|rym.abc.amar.com)'
